fixes:
    - "/home/runner/work/fmi_adapter_ros2/fmi_adapter_ros2/ros_ws/src/fmi_adapter_ros2/::"
ignore:
    - "fmi_adapter/src/fmi_adapter_node.cpp"
    - "fmi_adapter/test"
    - "fmi_adapter_examples"
